language: node_js

sudo: false

node_js:
  - '0.10'

env:
  global:
    - secure: G3az2JJAvaaR1W5qekB8RFPjIc+yQqkyRdJ+A4uGaS93K0vEqxEhET51TanADtwFYnf6DaPsoSKjG7gWxglsGjgDCqh8D+RD/F8TzDhbafJVui+oPEo1jx8TtBMDl8qBn6v3OMAN5YbB2eEW93IPb0eET8V7xPLdA4Ohu5iXdeI=
    - secure: NDVS5+wa7JqEvstCMWOSy23viZK6hI3LJWw4E11OzR2Cav/TOSaGXSrUVawg4xxx8YfBnxGgdlNdQZYGpotnH47dEsGASOiWcxXeCAScUDnAdNRtcRUf/PY0BdCSnwNvU/uqFLEA1SNX95NwrEY88Z+II9ebYiHSyMzeymMaLKI=

before_install:
  # Log HTTP requests
  - npm config set loglevel http

install:
  - time npm install
